
version: '3.8'

services:
  bankdb:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  bank:
    build: .
    ports:
      - "9999:9999"